/**
 * The axiom inventory, read from data/ablation.json.
 *
 * That file is generated by `axiom_sweep.py inventory`, which parses the two
 * Isabelle theory files. verify.sh section 4g regenerates it and fails if it
 * has drifted, so the fifty-one axioms on the website and the fifty-one
 * axioms the proof assistant checks cannot come apart.
 *
 * The verdicts are deliberately not in that file. They are measured by
 * verify.sh section 4, which re-runs Isabelle and Nitpick. A verdict cached in
 * a JSON file is a verdict nobody is checking.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { REPO_ROOT } from './content';

export interface Axiom {
  label: string;
  /** Isabelle escapes rendered as characters; unknown escapes left visible. */
  formula: string;
  /** Exactly as written in the theory file. */
  raw: string;
  sufficient: boolean;
  necessary: boolean;
  step_one: boolean;
}

export interface Ablation {
  generated_by: string;
  generated_from: string[];
  note: string;
  axioms: Axiom[];
  sufficient: string[];
  necessary: string[];
  step_one: string[];
  step_one_broken_scripts: string[];
  results: { theorems: string[]; amd1_lemmas: string[] };
}

const file: Ablation = JSON.parse(
  readFileSync(join(REPO_ROOT, 'data', 'ablation.json'), 'utf8'),
);

if (!file.axioms?.length) {
  throw new Error('data/ablation.json carries no axioms; run axiom_sweep.py inventory');
}

export const ablation = file;
export const axioms: readonly Axiom[] = file.axioms;

/** Look one up, failing loudly rather than rendering a blank. */
export function axiom(label: string): Axiom {
  const found = file.axioms.find((a) => a.label === label);
  if (!found) {
    throw new Error(
      `No axiom "${label}" in data/ablation.json. Have: ${file.axioms
        .map((a) => a.label)
        .join(', ')}`,
    );
  }
  return found;
}

/**
 * The three states the explorer can be in.
 *
 * `keeps` decides which of the fifty-one axioms are present. Everything a
 * state claims is a claim verify.sh re-runs; the `checkedBy` string names the
 * experiment so a reader can run it themselves.
 */
export interface AblationState {
  id: string;
  short: string;
  title: string;
  keeps: (a: Axiom) => boolean;
  checkedBy: string;
}

export const STATES: AblationState[] = [
  {
    id: 'full',
    short: 'The published model',
    title: 'All of it, exactly as Zahoransky and Benzm\u00fcller wrote it',
    keeps: () => true,
    checkedBy: 'axiom_sweep.py all',
  },
  {
    id: 'six',
    short: 'The six that suffice',
    title: 'Delete forty-five axioms and the dictatorship still follows',
    keeps: (a) => a.sufficient,
    checkedBy: 'axiom_sweep.py minimal, then tight',
  },
  {
    id: 'nostepone',
    short: "Delete G\u00f6del's step one",
    title: 'Remove the amendment that strips Article V, and see what breaks',
    keeps: (a) => !a.step_one,
    checkedBy: 'axiom_sweep.py noamd1, then repeal',
  },
];

/** How many axioms survive in a given state. Counted, never typed. */
export function kept(state: AblationState): number {
  return file.axioms.filter(state.keeps).length;
}
